# Generated by Django 3.2.5 on 2022-08-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('winery', models.CharField(max_length=50)),
                ('variety', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
