# Generated by Django 4.0.6 on 2022-08-09 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0002_wine_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wine',
            old_name='variety',
            new_name='varietal',
        ),
    ]
