# Generated by Django 3.2.5 on 2022-08-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0003_rename_variety_wine_varietal'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wines/'),
        ),
    ]
