# Generated by Django 3.2.5 on 2022-08-13 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varietal', '0002_auto_20220813_1941'),
        ('winery', '0001_initial'),
        ('wines', '0004_wine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='varietal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='varietal.varietal'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='winery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winery.winery'),
        ),
    ]
