# Generated by Django 4.1 on 2022-08-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0005_auto_20220813_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='aviable',
            field=models.BooleanField(default=True),
        ),
    ]
