# Generated by Django 3.2.5 on 2022-08-28 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0006_wine_aviable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wine',
            old_name='aviable',
            new_name='available',
        ),
    ]
