# Generated by Django 4.1 on 2022-08-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='varietal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('features', models.CharField(max_length=300)),
                ('type_grape', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('winery', models.CharField(max_length=70)),
                ('wine', models.CharField(max_length=50)),
            ],
        ),
    ]
